name: "Le CI de la mort"
on:
  pull_request:
    branches: [ "main" ]
    types: [ synchronize ]
jobs:
  it-has-one-job:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Set up PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql user: test
        postgresql password: password

    - name: Install gems
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
      env:
        DATABASE_URL: 'postgres://test:password@localhost/application_test'

    - name: Get file changes
      id: get_file_changes
      uses: trilom/file-changes-action@v1.2.4
      with:
        output: ' '
    - name: Echo file changes
      run: |
        echo Changed files: ${{ steps.get_file_changes.outputs.files }}

    - name: Run Rubocop
      id: rubocop_run
      run: bundle exec rubocop --force-exclusion ${{ steps.get_file_changes.outputs.files }}

    - name: Run whole RSpec suite
      id: rspec-id
      if: ${{ steps.rubocop_run.outputs.conclusion }} == "success"
      run: bundle exec rspec --fail-fast
