name: "My-Awesome-Workflow"
on:
  pull_request:
    branches: [ "main" ]
    types: [ synchronize ]
jobs:
  fais-tourner-les-specs:
    runs-on: ubuntu-latest
      needs: [ruby-set-up]
      steps:
        - name: Run specs
        run: bundle exec rspec --fail-fast
        env:
          DATABASE_URL: 'postgres://test:password@localhost/application_test'
