# name: "Rubocop-workflow"
# on:
#   pull_request:
#     branches: [ "main" ]
#     types: [ synchronize ]
# jobs:
#   rubocop-build:
#     runs-on: ubuntu-latest
#     if: ${{ !github.event.pull_request.draft }}
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3
#     - name: Install Ruby and gems
#       uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e
#       with:
#         bundler-cache: true

#     - name: Get file changes
#       id: get_file_changes
#       uses: trilom/file-changes-action@v1.2.4
#       with:
#         output: ' '
#     - name: Echo file changes
#       run: |
#         echo Changed files: ${{ steps.get_file_changes.outputs.files }}

#     - name: Rubocop
#       uses: wearerequired/lint-action@v2.1.0
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         rubocop: true
#         auto_fix: false
#         rubocop_args: --force-exclusion ${{ steps.get_file_changes.outputs.files}}
#         rubocop_command_prefix: bundle exec
